apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- patch: |-
    - op: replace
      path: /spec/hostnames/0
      value: s1.leven-lake.com
  target:
    kind: HTTPRoute
    name: httproute
images:
- name: ghcr.io/stefanprodan/podinfo
  newTag: 6.6.2
