apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- target:
    kind: HTTPRoute
    name: httproute
  patch: |-
    - op: replace
      path: /spec/hostnames/0
      value: p1.leven-lake.com
